### ISSUE TITLE
Not checking similar web content

### ISSUE THREAD

**Issue by improphethacker** [s0md3v/uro#14]
Hello,
This is not checking similar web content on many links. I will share the screenshot and URLs. Please fix it.
![image](https://user-images.githubusercontent.com/31764504/132986459-cc098450-2edb-4484-979a-5014fc80e15a.png)

**Comment by s0md3v** [comment]
It doesn't make any changes to the output file.

**Comment by improphethacker** [comment]
> It doesn't make any changes to the output file.

Yeah, I know that, I was showing my output file where you can see I tried using the tool but it didn't check "sonyservismerkezi" URL which is having similar content on both pages. I think you have misunderstood my screenshot.

**Comment by improphethacker** [comment]
Hello @s0md3v 
This is a duplicate issue, please ignore this.
