### ISSUE TITLE
Command 'uro' not found

### ISSUE THREAD

**Issue by harmony00x** [s0md3v/uro#21]
![image](https://user-images.githubusercontent.com/74853740/159118824-ef93b4bf-ffaa-41e4-af61-807209db14c6.png)
after installing 
`pip3 install uro 
`when use this command 
`cat url.txt | uro 
`it doesn't work as the photo

**Comment by s0md3v** [comment]
Try installing it as `pip3 install uro --user`

Close this issue if it works.

**Comment by harmony00x** [comment]
![image](https://user-images.githubusercontent.com/74853740/159137852-3a843249-108a-459d-a2f8-323019430a78.png)
the same issue 😞

**Comment by s0md3v** [comment]
I have no idea why it's not working for you. There must be something wrong with your PATH

**Comment by siriusblack01** [comment]
@s0md3v How can you just close an issue, while it has not resolved?!

**Comment by siriusblack01** [comment]
I solved this problem by installing `uro` in a virtual environment.

**Comment by parth2210** [comment]
> ![image](https://user-images.githubusercontent.com/74853740/159137852-3a843249-108a-459d-a2f8-323019430a78.png) the same issue 😞

I've got the same issue. Its not working for me as well

**Comment by vampvaibhav** [comment]
Navigate to the location where uro is installed. Then type "cp uro /usr/bin". It will definitely work after this.

**Comment by pr0xy-exe** [comment]
Try cloning the repo and install using,
`python setup.py install`

worked for me.

**Comment by campelohunter** [comment]
python3.11 setup.py install or pipx install uro

**Comment by gkarumbi** [comment]
install it in a virtualized environment. it worked for me.

**Comment by 1nightdev** [comment]
simply use: pipx install uro

**Comment by 0x00er** [comment]
add your path to the shell

echo 'export PATH=$PATH:$HOME/.local/bin' >> ~/.zshrc
source ~/.zshrc

**Comment by campelohunter** [comment]
thanks brow

________________________________
De: Sagar Verma ***@***.***>
Enviado: domingo, 21 de setembro de 2025 11:45
Para: s0md3v/uro ***@***.***>
Cc: campelohunter.io ***@***.***>; Comment ***@***.***>
Assunto: Re: [s0md3v/uro] Command 'uro' not found (Issue #21)

[https://avatars.githubusercontent.com/u/112767069?s=20&v=4]0x00er left a comment (s0md3v/uro#21)<https://github.com/s0md3v/uro/issues/21#issuecomment-3315942182>

add your path to the shell

echo 'export PATH=$PATH:$HOME/.local/bin' >> ~/.zshrc
source ~/.zshrc
