### ISSUE TITLE
When using uro on subdomains it leaves :// in front?

### ISSUE THREAD

**Issue by gprime31** [s0md3v/uro#26]
When using uro on subdomains it leaves :// in front

example:

cat subs.txt | uro

subs.txt example:
site.com
sub.site.com
sub123.site.com

anything without http:// or https:// in front it leaves the :// in front.

**Comment by gprime31** [comment]
example:

assetfinder -subs-only example.com | uro


![2022-08-18_10-43](https://user-images.githubusercontent.com/44535257/185423813-e4b03846-4a90-4460-a71a-dba309591eb9.png)

**Comment by s0md3v** [comment]
uro's documentation clearly states that it's designed for URLs since they are hard to de-duplicate unlike simple strings such as subdomains. This is an invalid issue and will not be "fixed".
