### ISSUE TITLE
uro error 

### ISSUE THREAD

**Issue by Iamsajidkhan** [s0md3v/uro#30]
**cat urls.txt | uro > test**

Traceback (most recent call last):
  File "/usr/local/bin/uro", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/uro/uro.py", line 123, in main
    for line in sys.stdin:
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

@s0md3v

**Comment by Karthik-HR0** [comment]
Use this github.com/Karthik-HR0/uro

**Comment by Karthik-HR0** [comment]
> **cat urls.txt | uro > test**
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/uro", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.10/dist-packages/uro/uro.py", line 123, in main
>     for line in sys.stdin:
>   File "/usr/lib/python3.10/codecs.py", line 322, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
> 
> 
> 
> @s0md3v 

Use this tool GitHub.com/Karthik-HR0/uro

**Comment by s0md3v** [comment]
This issue has been fixed in latest release (v1.0.1).
