### ISSUE TITLE
Unable to install URO

### ISSUE THREAD

**Issue by Gokul7777777** [s0md3v/uro#34]
I used pip command but not installed.

It shows :

Requirement already satisfied: uro in ./.local/lib/python3.11/site-packages (1.0.0)

**Comment by khorzokhanorg** [comment]
cd  ./.local/lib/python3.11/site-packages 
Delete two related files or folders uro

now start install again by pip : (dont install by pip3 )
pip install uro --user

now work (👍 : 
uro -h
