### ISSUE TITLE
I get a warning when installing uro with pip

### ISSUE THREAD

**Issue by Krmorc** [s0md3v/uro#35]
![resim_2023-05-13_145950535](https://github.com/s0md3v/uro/assets/43620287/71bec5aa-9c78-49ea-a285-12caa272000e)

Hello, in older versions of Kalin, I used to write 'pip3 install uro --user' and could directly use Uro. Now, I'm getting a warning as shown in the screenshot on SS and I can't use it. Can you help me with what I need to do?

**Comment by s0md3v** [comment]
Try without the --user flag.
