### ISSUE TITLE
--filters noexts   Not working

### ISSUE THREAD

**Issue by wyxxl** [s0md3v/uro#39]
![image](https://github.com/s0md3v/uro/assets/26040426/de89a990-a014-4dde-a274-63590fc4d554)

**Comment by azizp128** [comment]
"--filters params" also doesn't work. It doesn't remove any incremental urls.

**Comment by s0md3v** [comment]
@wyxxl This was a mistake in the README. It's `noext` and `hasext`, not `noexts` and `hasexts`.

@pr0b35 You have misread, there's no filter called `params`.
